//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int client { get; set; }
        public int product { get; set; }
        public int manager { get; set; }
        public double sum { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Managers Managers { get; set; }
    }
}
